### ISSUE TITLE
推荐使用这个真正的个人支付接口，支持pc扫码、微信浏览器、手机H5端支付

### ISSUE THREAD

**Issue by opppp8** [zlkbdotnet/zfaka#224]
目前已经支持zfaka系统，支持pc扫码、微信浏览器、手机H5端支付，顾客体验非常好：https://h5zhifu.com

**Comment by kobefaka** [comment]
楼上QQ群进不去啊！帮我设置下接口！

**Comment by bimoe** [comment]
注意骗子，到处碰瓷

**Comment by opppp8** [comment]
请问是有什么误会吗，不知道上面为什么说骗子，已经有很多用户在使用我们的接口了，目前都是没问题的

**Comment by kobefaka** [comment]
回复错了吧。发自我的iPhone------------------ 原始邮件 ------------------发件人: opppp8  ***@***.***>发送时间: 2021年4月18日 17:42收件人: zlkbdotnet/zfaka ***@***.***>抄送: kobefaka ***@***.***>, Comment ***@***.***>主题: 回复：[zlkbdotnet/zfaka] 推荐使用这个真正的个人支付接口，支持pc扫码、微信浏览器、手机H5端支付 (#224)
请问是有什么误会吗，不知道上面为什么说骗子，已经有很多用户在使用我们的接口了，目前都是没问题的

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/zlkbdotnet/zfaka/issues/224#issuecomment-821963104",
"url": "https://github.com/zlkbdotnet/zfaka/issues/224#issuecomment-821963104",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Imcaochang** [comment]
建议大家使用一些第三方支付时候查询一下这个支付的资质哦  我查了一下这个域名备案也没有 注册信息也是21年的....

**Comment by zlkbdotnet** [comment]
第三方支付请大家自行甄别
